version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tradewave-postgres
    environment:
      POSTGRES_DB: tradewave_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 190512
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tradewave-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tradewave-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tradewave_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 190512
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tradewave-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  tradewave-network:
    driver: bridge

