# Server
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tradewave_db
spring.datasource.username=postgres
spring.datasource.password=190512
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Message Encoding
spring.messages.encoding=UTF-8

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=muratguven376@gmail.com
spring.mail.password=gznhjudzpuylogrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


jwt.secret=A7sd89sdu1uAS89d1uQWek21MZx9uU1x
jwt.secret.base64=false
jwt.expiration=3600000
jwt.clockSkewSeconds=60